framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: shopq/pricewatch

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        app: cache.adapter.filesystem

        # Doctrine cache pools for production
        pools:
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
