framework:
    rate_limiter:
        domain_scraper:
            policy: sliding_window
            limit: 10
            interval: '1 hour'

        validate_endpoint:
            policy: sliding_window
            limit: 10
            interval: '1 minute'

        check_all_user:
            policy: fixed_window
            limit: 1
            interval: '15 minutes'

        registration_endpoint:
            policy: fixed_window
            limit: 3
            interval: '1 hour'

        password_reset_endpoint:
            policy: fixed_window
            limit: 3
            interval: '15 minutes'

        resend_verification_endpoint:
            policy: fixed_window
            limit: 3
            interval: '15 minutes'

        subscribe_endpoint:
            policy: sliding_window
            limit: 10
            interval: '1 hour'
